/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppProjectsRouteImport } from './routes/_app.projects'
import { Route as AppMissionsRouteImport } from './routes/_app.missions'
import { Route as AppKnowledgeRouteImport } from './routes/_app.knowledge'
import { Route as AppIntegrationsRouteImport } from './routes/_app.integrations'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppAiModelsRouteImport } from './routes/_app.ai-models'
import { Route as AppMissionsMissionIdRouteImport } from './routes/_app.missions.$missionId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppMissionsRoute = AppMissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeRoute = AppKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppAiModelsRoute = AppAiModelsRouteImport.update({
  id: '/ai-models',
  path: '/ai-models',
  getParentRoute: () => AppRoute,
} as any)
const AppMissionsMissionIdRoute = AppMissionsMissionIdRouteImport.update({
  id: '/$missionId',
  path: '/$missionId',
  getParentRoute: () => AppMissionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/ai-models': typeof AppAiModelsRoute
  '/home': typeof AppHomeRoute
  '/integrations': typeof AppIntegrationsRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/missions': typeof AppMissionsRouteWithChildren
  '/projects': typeof AppProjectsRoute
  '/missions/$missionId': typeof AppMissionsMissionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/ai-models': typeof AppAiModelsRoute
  '/home': typeof AppHomeRoute
  '/integrations': typeof AppIntegrationsRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/missions': typeof AppMissionsRouteWithChildren
  '/projects': typeof AppProjectsRoute
  '/missions/$missionId': typeof AppMissionsMissionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/ai-models': typeof AppAiModelsRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/integrations': typeof AppIntegrationsRoute
  '/_app/knowledge': typeof AppKnowledgeRoute
  '/_app/missions': typeof AppMissionsRouteWithChildren
  '/_app/projects': typeof AppProjectsRoute
  '/_app/missions/$missionId': typeof AppMissionsMissionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/ai-models'
    | '/home'
    | '/integrations'
    | '/knowledge'
    | '/missions'
    | '/projects'
    | '/missions/$missionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/ai-models'
    | '/home'
    | '/integrations'
    | '/knowledge'
    | '/missions'
    | '/projects'
    | '/missions/$missionId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/_app/ai-models'
    | '/_app/home'
    | '/_app/integrations'
    | '/_app/knowledge'
    | '/_app/missions'
    | '/_app/projects'
    | '/_app/missions/$missionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/missions': {
      id: '/_app/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof AppMissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/knowledge': {
      id: '/_app/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AppKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations': {
      id: '/_app/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-models': {
      id: '/_app/ai-models'
      path: '/ai-models'
      fullPath: '/ai-models'
      preLoaderRoute: typeof AppAiModelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/missions/$missionId': {
      id: '/_app/missions/$missionId'
      path: '/$missionId'
      fullPath: '/missions/$missionId'
      preLoaderRoute: typeof AppMissionsMissionIdRouteImport
      parentRoute: typeof AppMissionsRoute
    }
  }
}

interface AppMissionsRouteChildren {
  AppMissionsMissionIdRoute: typeof AppMissionsMissionIdRoute
}

const AppMissionsRouteChildren: AppMissionsRouteChildren = {
  AppMissionsMissionIdRoute: AppMissionsMissionIdRoute,
}

const AppMissionsRouteWithChildren = AppMissionsRoute._addFileChildren(
  AppMissionsRouteChildren,
)

interface AppRouteChildren {
  AppAiModelsRoute: typeof AppAiModelsRoute
  AppHomeRoute: typeof AppHomeRoute
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppKnowledgeRoute: typeof AppKnowledgeRoute
  AppMissionsRoute: typeof AppMissionsRouteWithChildren
  AppProjectsRoute: typeof AppProjectsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiModelsRoute: AppAiModelsRoute,
  AppHomeRoute: AppHomeRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppKnowledgeRoute: AppKnowledgeRoute,
  AppMissionsRoute: AppMissionsRouteWithChildren,
  AppProjectsRoute: AppProjectsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
